import type { CodeList } from "../types.js";

export const EAS_3: CodeList = [
	{
		code: "0002",
		name: "System Information et Repertoire des Entreprise et des Etablissements: SIRENE",
	},
	{ code: "0007", name: "Organisationsnummer" },
	{ code: "0009", name: "SIRET-CODE" },
	{ code: "0037", name: "LY-tunnus" },
	{ code: "0060", name: "Data Universal Numbering System (D-U-N-S Number)" },
	{ code: "0088", name: "EAN Location Code" },
	{ code: "0096", name: "DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)" },
	{ code: "0097", name: "FTI - Ediforum Italia, (EDIRA compliant)" },
	{
		code: "0106",
		name: "Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)",
	},
	{ code: "0130", name: "Directorates of the European Commission" },
	{ code: "0135", name: "SIA Object Identifiers" },
	{ code: "0142", name: "SECETI Object Identifiers" },
	{ code: "0151", name: "Australian Business Number (ABN) Scheme" },
	{
		code: "0183",
		name: "Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB) ",
	},
	{ code: "0184", name: "DIGSTORG" },
	{
		code: "0190",
		name: "Dutch Originator's Identification Number",
		description: "Replaces 9954",
	},
	{
		code: "0191",
		name: "Centre of Registers and Information Systems of the Ministry of Justice",
	},
	{
		code: "0192",
		name: "Enhetsregisteret ved Bronnoysundregisterne ",
		description: "Replaces 9908",
	},
	{ code: "0193", name: "UBL.BE party identifier" },
	{ code: "0194", name: "KOIOS Open Technical Dictionary" },
	{ code: "0195", name: "Singapore UEN identifier" },
	{
		code: "0196",
		name: "Kennitala - Iceland legal id for individuals and legal entities",
		description: "Replaces 9917",
	},
	{ code: "0198", name: "ERSTORG" },
	{ code: "0199", name: "Legal Entity Identifier (LEI)" },
	{ code: "0200", name: "Legal entity code (Lithuania)" },
	{
		code: "0201",
		name: "Codice Univoco Unità Organizzativa iPA",
		description: "Replaces 9921",
	},
	{ code: "0202", name: "Indirizzo di Posta Elettronica Certificata" },
	{ code: "0203", name: "eDelivery Network Participant identifier" },
	{ code: "0204", name: "Leitweg-ID", description: "Replaces 9958" },
	{
		code: "0208",
		name: "Numero d'entreprise / ondernemingsnummer / Unternehmensnummer",
	},
	{ code: "0209", name: "GS1 identification keys" },
	{ code: "0210", name: "CODICE FISCALE" },
	{ code: "0211", name: "PARTITA IVA" },
	{ code: "0212", name: "Finnish Organization Identifier" },
	{ code: "0213", name: "Finnish Organization Value Add Tax Identifier" },
	{ code: "9901", name: "Danish Ministry of the Interior and Health" },
	{ code: "9902", name: "The Danish Commerce and Companies Agency " },
	{
		code: "9904",
		name: "Danish Ministry of Taxation, Central Customs and Tax Administration",
	},
	{ code: "9905", name: "Danish VANS providers " },
	{ code: "9906", name: "Ufficio responsabile gestione partite IVA " },
	{ code: "9907", name: "TAX Authority " },
	{ code: "9910", name: "Hungary VAT number" },
	{ code: "9913", name: "Business Registers Network " },
	{ code: "9914", name: "Österreichische Umsatzsteuer-Identifikationsnummer " },
	{
		code: "9915",
		name: "Österreichisches Verwaltungs bzw. Organisationskennzeichen",
	},
	{
		code: "9917",
		name: "Kennitala - Iceland legal id for organizations and individuals",
		description: "Replaced by 0196",
	},
	{
		code: "9918",
		name: "SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T",
	},
	{ code: "9919", name: "Kennziffer des Unternehmensregisters " },
	{ code: "9920", name: "Agencia Española de Administración Tributaria " },
	{
		code: "9921",
		name: "Indice delle Pubbliche Amministrazioni ",
		description: "Replaced by 0201",
	},
	{ code: "9922", name: "Andorra VAT number" },
	{ code: "9923", name: "Albania VAT number" },
	{ code: "9924", name: "Bosnia and Herzegovina VAT number" },
	{ code: "9925", name: "Belgium VAT number" },
	{ code: "9926", name: "Bulgaria VAT number" },
	{ code: "9927", name: "Switzerland VAT number" },
	{ code: "9928", name: "Cyprus VAT number" },
	{ code: "9929", name: "Czech Republic VAT number" },
	{ code: "9930", name: "Germany VAT number" },
	{ code: "9931", name: "Estonia VAT number" },
	{ code: "9932", name: "United Kingdom VAT number" },
	{ code: "9933", name: "Greece VAT number" },
	{ code: "9934", name: "Croatia VAT number" },
	{ code: "9935", name: "Ireland VAT number" },
	{ code: "9936", name: "Liechtenstein VAT number" },
	{ code: "9937", name: "Lithuania VAT number" },
	{ code: "9938", name: "Luxemburg VAT number" },
	{ code: "9939", name: "Latvia VAT number" },
	{ code: "9940", name: "Monaco VAT number" },
	{ code: "9941", name: "Montenegro VAT number" },
	{
		code: "9942",
		name: "Macedonia, the former Yugoslav Republic of VAT number",
	},
	{ code: "9943", name: "Malta VAT number" },
	{ code: "9944", name: "Netherlands VAT number" },
	{ code: "9945", name: "Poland VAT number" },
	{ code: "9946", name: "Portugal VAT number" },
	{ code: "9947", name: "Romania VAT number" },
	{ code: "9948", name: "Serbia VAT number" },
	{ code: "9949", name: "Slovenia VAT number" },
	{ code: "9950", name: "Slovakia VAT number" },
	{ code: "9951", name: "San Marino VAT number" },
	{ code: "9952", name: "Turkey VAT number" },
	{ code: "9953", name: "Holy See (Vatican City State) VAT number" },
	{ code: "9955", name: "Swedish VAT number" },
	{
		code: "9956",
		name: "Belgian Crossroad Bank of Enterprises ",
		description: "Replaced by 0208",
	},
	{ code: "9957", name: "French VAT number" },
	{ code: "9958", name: "German Leitweg ID", description: "Replaced by 0204" },
	{ code: "AN", name: "O.F.T.P. (ODETTE File Transfer Protocol)" },
	{ code: "AQ ", name: "X.400 address for mail text" },
	{ code: "AS ", name: "AS2 exchange " },
	{ code: "AU ", name: "File Transfer Protocol" },
	{ code: "EM", name: "Electronic mail", description: "SMTP email" },
];
